### ISSUE TITLE
Animation doesn't match iOS physics 

### ISSUE THREAD

**Issue by devindoty** [jaredsinclair/JTSSloppySwiping#2]
Would be nice if the [push animation](https://github.com/jaredsinclair/JTSSloppySwiping/blob/master/JTSSloppySwiping/JTSSloppySwiping.swift#L211) used a spring animation to match iOS physics. Pop should be okay when triggered from a gesture since the duration is halved, but I would guess its too fast from a tap.

Apple uses .5 duration and .85-.9 damping for all view controller transitions.

**Comment by jaredsinclair** [comment]
Shit, thanks for the reminder. I think it actually regular block based animations, but with an undocumented animation option (and animation curve). The option's raw value is (or was) something like `7 << 16`. I’m still trying to figure out how to hack this with Swift 2.0. It might not be possible.

**Comment by jaredsinclair** [comment]
OMG fixed this by deleting the non-interactive animator. I’d forgotten I could just return `nil` and the system default animations would take over as a fallback.

**Comment by devindoty** [comment]
🙌🏻

7 << 16 ends up adding a `CASpringAnimation` that looks like this 

`<CASpringAnimation:0x7f9112ed9d00; delegate = <UIViewAnimationState: 0x7f9112ed8330>; fillMode = both; timingFunction = linear; duration = 0.5; velocity = 0; damping = 500; stiffness = 1000; mass = 3>`

**Comment by jaredsinclair** [comment]
It's 7<< 16 for keyboard appearance and 6 << 16 for KB disappearance if memory serves. I'm only guessing that UINC push/pop do the same, since they feel similar.
