### ISSUE TITLE
Shortens scrollview on swipe

### ISSUE THREAD

**Issue by AaronKovacs** [jaredsinclair/JTSSloppySwiping#6]
So I have two views connected to each other through the Sloppy Swipe navigational controller the one you swipe back from is a tableviewcontroller with scrollview. Now as soon as you activate the swipe back interactive transition it can be seen that the scrollview jerks down a certain amount, so now if you cancel the gesture the scroll view seems to be inset at the top. As in if you have a scrollview that has 3 cells A,B,C and the scrollview top is supposed to be at the top of the first cell (A) now the scrollview starts at the top of cell (B) yet you can still see A  but it bounces back down to B.

**Comment by AaronKovacs** [comment]
Settings your view controller setting of "Under opaque bars" to true fixes this issue.

**Comment by mergesort** [comment]
It might be iOS 10 related, but I'm seeing this too now. I tried every option of true and false for `extendedLayoutIncludesOpaqueBars` and `edgesForExtendedLayout`, and still after I start swiping, the inset at the top begins to protrude (and stays forever).

Any thoughts @Arko4576 or @jaredsinclair?
